### ISSUE TITLE
Vue is not defined in services/auth.js

### ISSUE THREAD

**Issue by arysom** [dgrubelic/vue-authenticate#10]
According to your vue-authenticate-site project I can make service to instate new VueAuthenticate object and later import somewhere else. Problem is, that Vue is not defined here. If I console.log(Vue) it says, that it's a constructor. Should I make new Vue object?

My services/auth.js: 

```
import Vue from 'vue'
import VueResource from 'vue-resource'
import VueAuthenticate from 'vue-authenticate'
Vue.use(VueResource)

const vueAuthInstance = new VueAuthenticate(Vue.http, {
  baseUrl: 'http://localhost:8000',
  loginUrl: '/oauth/token'
})

export default vueAuthInstance
```

In main.js I have Vue of course.

```
new Vue({
  el: '#app',
  router,
  i18n,
  store
});
```

**Comment by dgrubelic** [comment]
Why are you passing `Vue.$http` to VueAuthenticate constructor? In demo site example i pass `Vue.http` and that works fine.

This is to what property plugin loading is binding http client to:
https://github.com/pagekit/vue-resource/blob/develop/src/index.js#L20

Also, there is no need to import `Vuex`in this `services/auth.js` service. I guess you will define your store instance somewhere else, so there place should be enough to import and initialize Vuex.

**Comment by arysom** [comment]
updated my source, still the same problem, maybe it has to do something with babel/webpack? I'm using es2015 preset.

**Comment by dgrubelic** [comment]
Well, for demo site i'm using webpack + es2015 babel preset, too, and everything is ok. I guess that it is your compiler or linter that is causing the problem.

**Comment by arysom** [comment]
Wait, I;m almost there, It went further without braces around {VueAuthenticate}, and the instance seem to create, but... in store/auth.js it gets me error on login action _auth2.default.login is not a function. Context and payload with my data appear there.

**Comment by dgrubelic** [comment]
Please install v1.2.2 until i see what the problem is with Vue being not defined. What does your store code looks like?

**Comment by arysom** [comment]
As in your app. The Vue is not defined is ok now, but in store.js, vueAuthInstance - login is not a function. I'll try with earlier version now.

```
import vueAuthInstance from '../services/auth.js'

export default {
  state: {
    profile: null
    //isAuthenticated: vueAuthInstance.isAuthenticated()
  },

  mutations: {
    isAuthenticated (state, payload) {
      state.isAuthenticated = payload.isAuthenticated
    },

    setProfile (state, payload) {
      state.profile = payload.profile
    }
  },

  actions: {
    login (context, payload) {
      payload = payload || {}
      return vueAuthInstance.login(payload.user, payload.requestOptions).then(function () {
        context.commit('isAuthenticated', {
          isAuthenticated: vueAuthInstance.isAuthenticated()
        })
      })
    },

    register (context, payload) {
      payload = payload || {}
      return vueAuthInstance.register(payload.user, payload.requestOptions).then(function () {
        context.commit('isAuthenticated', {
          isAuthenticated: vueAuthInstance.isAuthenticated()
        })
      })
    },

    logout (context, payload) {
      payload = payload || {}
      return vueAuthInstance.logout(payload.requestOptions).then(function () {
        context.commit('isAuthenticated', {
          isAuthenticated: vueAuthInstance.isAuthenticated()
        })
      })
    },

    authenticate (context, payload) {
      payload = payload || {}
      return vueAuthInstance.authenticate(payload.provider, payload.userData, payload.requestOptions).then(function () {
        context.commit('isAuthenticated', {
          isAuthenticated: vueAuthInstance.isAuthenticated()
        })
      })
    }
  }
}
```

**Comment by dgrubelic** [comment]
What does `console.log(vueAuthInstance)`says?

**Comment by arysom** [comment]
earlier ver does the same, cl in login function says: plugin () . As I go deeper there is for example function ($http, options), installed:true, but can't see login function.

**Comment by dgrubelic** [comment]
You need to import it like this to create new instance:

```javascript
import { VueAuthenticate } from 'vue-authenticate'
```

since that will get you VueAuthenticate class, without `{}`you get Vue plugin initialization method.

If you import it without `{}` like this:

```javascript
import VueAuthenticate from 'vue-authenticate'
```
you can use:

```javascript
const vueAuthInstance = VueAuthenticate.factory($http, options)
```

**Comment by arysom** [comment]
I understand that it wasn't vue-auth instance, only Vue method. But now I still get Vue is not defined, do I can't pass Vue.http to arguments.

```
import Vue from 'vue'
import VueResource from 'vue-resource'
import { VueAuthenticate }  from 'vue-authenticate'
Vue.use(VueResource)

const vueAuthInstance = new VueAuthenticate(Vue.http, { ...
```

**Comment by dgrubelic** [comment]
Ok, I'll check it out later, i'm not able to do it now.

**Comment by arysom** [comment]
No problem, if I'll find solution, I'll share here

**Comment by arysom** [comment]
got back to vue-authenticate 1.1.0 as in demo, and now works, using 1.1.0 for now

**Comment by dgrubelic** [comment]
I have come to a conclusion that your build configuration needs some work. Just now, i tried to setup CommonJS example. Basically, you need to setup correct library sources because if you use default webpack configuration, for some library you'll get ES6 version compiled, for some CommonJS.. If that happens, you either need to fix resolve aliases (go to solution) or you need to be careful when importing libs:

If you get ES6 source compiled , you have to do something like this:

```javascript
var Vue = require('vue')
var Vuex = require('vuex').default
```

This is because, although i'm compiling CommonJS source, Vuex get me ES6 version of file. I think that this is what caused you problems today.

BTW, i updated to v1.2.4 which should remove "Vue is not defined" error.

**Comment by arysom** [comment]
I'm quite new to ES6 world and thanks to your app I've already learned a lot. I'm using[ laravel-mix](https://github.com/JeffreyWay/laravel-mix) as standalone webpack,so maybe I'll have to take a closer look into configuration.

I'll try new version on Tuesday. Happy Easter!

**Comment by arysom** [comment]
Its working now. Thank you!
