### ISSUE TITLE
Redirect not working and Popup not closing in production

### ISSUE THREAD

**Issue by therealwolf42** [dgrubelic/vue-authenticate#100]
Everything works in development environment, but when I build it for production, the redirect after the popup doesn't work. The popup also doesn't get closed.

The project I'm working on is open-source so I'd really appreciate it if you could take a look.

https://github.com/utopian-io/signup.utopian.io/blob/master/src/store/store.js#L22

And here is it in production:

https://signup.utopian.io/

**Comment by dgrubelic** [comment]
Any info on this issue? Have you managed to fix it?

**Comment by therealwolf42** [comment]
@dgrubelic 
Problem has been fixed after re-writing the NGINX-config which somehow messed up the redirect to https. Thank you for the help!!
