### ISSUE TITLE
isAuthenticated false after page reload

### ISSUE THREAD

**Issue by rico** [dgrubelic/vue-authenticate#101]
Is it normal that I loose the authentication status after a page reload ?

I have set up the library to use vuex. Login works - state ist set, but on page reload `isAuthenticated` is `false`. The token can still be found in `Local Storage`.

**Comment by dgrubelic** [comment]
Can you gist your `vuex` & `vue-authenticate` code?

**Comment by rico** [comment]
Sure - https://gist.github.com/rico/57b1b5a6af51ff20eee0c9ee4a6ed8e3

... many thanks for your help. And sorry if it is a stupid mistake - im a novice in frontend dev.

**Comment by dgrubelic** [comment]
I thought this might be the issue: https://gist.github.com/rico/57b1b5a6af51ff20eee0c9ee4a6ed8e3#file-auth-js-L8

You'll need to set state property default value from VueAuthenticate instance, in this case that is `authProvider` variable:

```
const state = {
    isAuthenticated: authProvider.isAuthenticated(),
    user: null // Also, load user data from localStorage too (you have to make sure it is stored there after login)
};
```

**Comment by rico** [comment]
Thanks - makes sense :-)
