### ISSUE TITLE
Using social authentication with a similar flow to Hello.js

### ISSUE THREAD

**Issue by aidanayala** [dgrubelic/vue-authenticate#105]
For social authentication It seems like we have to send a client secret from our own server after clicking "login"

This doesn't happen when using libs like Hello.js

Is it possible for us to simply just get an access token without having to supply a client secret?

**Comment by dgrubelic** [comment]
This is bacause Hello.js is using implicit OAuth flow by default. You can change it by changing `response_type` to be `token`. Implicit flow returns token right after you login using your social credentials.

![screen shot 2018-02-26 at 5 01 37 pm](https://user-images.githubusercontent.com/1304876/36680689-c58da3fc-1b16-11e8-894c-bc3a79537488.png)

This library uses explicit flow by default which returns code first, and then you need to do exchange for token using your own server implementation. This is more secure process. But, you can change it by changing `responseType` to `token` in your provider configuration.

**Comment by aidanayala** [comment]
Thank you
