### ISSUE TITLE
Uncaught TypeError: Cannot read property 'authenticate' of undefined

### ISSUE THREAD

**Issue by JamesJefferyUK** [dgrubelic/vue-authenticate#107]
I'm getting the following error:

<img width="791" alt="screen shot 2018-02-28 at 20 17 21" src="https://user-images.githubusercontent.com/19844560/36811094-91efa856-1cc4-11e8-8d4a-0917c3ae4545.png">

Here is my `App.vue` file:

```
<template>
  <div id="app">
    <button @click="auth('facebook')">Login with Facebook</button>
  </div>
</template>

<script>
export default {
  name: 'app',
  methods: {
    auth: (provider) => 
      this.$auth.authenticate(provider)
      .then(() => console.log('Authenticated')),
  },
}
</script>

```

And here is `index.js`:

```
import Vue from 'vue';
import VueAuthenticate from 'vue-authenticate';
import config from './config';
import App from './App.vue';

Vue.config.productionTip = false;

Vue.use(VueAuthenticate, {
  baseUrl: `${config.protocol}://${config.domain}`,
  providers: {
    facebook: {
      clientId: config.fb_client_id,
      redirectUri: `${config.protocol}://${config.domain}/auth/callback`,
    },
  },
});

new Vue({
  render: h => h(App),
}).$mount('#app');
```

Any idea why this may be?

**Comment by JamesJefferyUK** [comment]
Changing from fat arrows, to regular anonymous functions fixed it. But why? I am assuming this has something to do with scoping.

```
 auth: function(provider) {
      this.$auth.authenticate(provider).then(() =>
        console.log('Authenticated')
      );
 }
```

**Comment by JamesJefferyUK** [comment]
I was right. When using fat arrows on the top level methods it changes the scope of `this`. Discussed here: https://m.dotdev.co/clean-up-your-vue-modules-with-es6-arrow-functions-2ef65e348d41

**Comment by dgrubelic** [comment]
You can either use ES5 functions or ES6 methods:

```
<script>
export default {
  name: 'app',
  methods: {
    auth: function (provider) {
      this.$auth.authenticate(provider)
      .then(() => console.log('Authenticated')),
    }
  },
}
</script>
```

or

```
<script>
export default {
  name: 'app',
  methods: {
    auth(provider) {
      this.$auth.authenticate(provider)
      .then(() => console.log('Authenticated')),
    }
  },
}
</script> 
```

but not arrow functions like you did in the first example because `this` will have reference to the outer scope. You most definitely didn't follow documentation because the documentation doesn't use arrow functions but ES5 functions.
