### ISSUE TITLE
Possible Unhandled Promise Rejection: Error: Authentication failed

### ISSUE THREAD

**Issue by solidevolution** [dgrubelic/vue-authenticate#113]
Since today, i got the following error in my develop system (docker, webpack, vue-cli)

It still works on production, the only difference from dev system is:
- not available from outside
- no ssl

Here more information about the error:

<img width="488" alt="bildschirmfoto 2018-03-14 um 17 29 08" src="https://user-images.githubusercontent.com/6850773/37416160-5d7c995a-27ad-11e8-82d9-2e8bd7b5fb3c.png">
<img width="489" alt="bildschirmfoto 2018-03-14 um 17 29 39" src="https://user-images.githubusercontent.com/6850773/37416171-620c5ab4-27ad-11e8-8a4f-23776df24c20.png">
<img width="486" alt="bildschirmfoto 2018-03-14 um 17 29 55" src="https://user-images.githubusercontent.com/6850773/37416178-65c1592a-27ad-11e8-9905-c7bf5817e9c4.png">

The only thing that changed:

https://developers.facebook.com/blog/post/2017/12/18/strict-uri-matching/
https://developers.facebook.com/docs/facebook-login/security/#strict_mode

But I integrated the URIs for strict mode already in december.

**Comment by billowapp** [comment]
Getting the exact same error here.

**Comment by dgrubelic** [comment]
Thanks for reporting this. Can you inspect response you get because, since error is thrown in `.then()`, it probably just didn't found token in your response. Can you paste your response here?

**Comment by solidevolution** [comment]
@dgrubelic can't reproduce it now, sorry.

**Comment by billowapp** [comment]
Thanks for getting back so quickly @dgrubelic 

herewith my server response

<img width="1055" alt="screen shot 2018-03-20 at 13 38 32" src="https://user-images.githubusercontent.com/11815088/37652421-2722bd44-2c44-11e8-8982-f2f441dbef08.png">

and herewith the error i receive

<img width="572" alt="screen shot 2018-03-20 at 13 38 45" src="https://user-images.githubusercontent.com/11815088/37652430-2df526ac-2c44-11e8-8007-1838805c7bcf.png">

herewith my handler

<img width="609" alt="screen shot 2018-03-20 at 13 40 27" src="https://user-images.githubusercontent.com/11815088/37652473-4962c73c-2c44-11e8-8e56-189cd7021b49.png">

I must add that im using laravel passport in conjunction with socialite, everything is working perfectly on the server side its just when returning the token that things fall over in the "then" of the promise.

**Comment by dgrubelic** [comment]
Have you changed you token name in provider configuration? https://github.com/dgrubelic/vue-authenticate/blob/master/src/options.js#L26

**Comment by billowapp** [comment]
@dgrubelic the token name was the issue, thanks so much for the assistance.

**Comment by Justinio99** [comment]
@billowapp Where can you change the token name and who does a token name look like?

**Comment by billowapp** [comment]
@Justinio99, you'll see in the response screenshot i posted above that it was sending me back a `p_token` field instead of `token`

**Comment by Justinio99** [comment]
@billowapp i don't know why, but we don't get a response

**Comment by Ethan0007** [comment]
Hi,

I have same issue, i don't have response.

![image](https://user-images.githubusercontent.com/12542052/50424806-4579ab00-089d-11e9-8c28-e3e26d4fb5b4.png)

![image](https://user-images.githubusercontent.com/12542052/50424809-55918a80-089d-11e9-995e-166a85f31445.png)

I'm using .net core 2.1, do i need to create controller for redirectUri or just only a page for a callback?

Thanks.

**Comment by diadal** [comment]
@solidevolution please can you explain how you get response from `/auth/facebook/callback`
 am using socialite for backend but not able to get the response 

```
AuthProvider(p) {
              this.$auth.authenticate(p).then(response =>{
                                console.log(response)
                
                }).catch(err => {
                    console.log({err:err})
                })

            },
```

**Comment by solidevolution** [comment]
@diadal we use https://github.com/requests/requests-oauthlib.
Sorry but I can't help more because I didn't worked "Full Stack" on this.

**Comment by diadal** [comment]
this solve my issue I create new package for laravel Vue (SPA) it work anyone can give it try 

https://github.com/diadal/vue-social-auth

**Comment by solidevolution** [comment]
@diadal perfect, good work.
I hope your package get a lot of reputation and feedback from the laravel community!

**Comment by aren1989** [comment]
I think you need to set 'p_token' to "tokenPath" in provider config like this
`providers: {
      facebook: {
        tokenPath: 'p_token',
        clientId: ''  // Your client ID,
        redirectUri: '' // Your client app URL
      }
    }`
