### ISSUE TITLE
Facebook no longer works with popup

### ISSUE THREAD

**Issue by kieraneglin** [dgrubelic/vue-authenticate#116]
I'm not sure when this happened, but within the last few days Facebook OAuth requests will open in a new tab instead of the popup.

**Comment by kieraneglin** [comment]
My apologies, it was caused by Firefox's Facebook container plugin!  Vue-authenticate works as expected.

As an aside, you may want to change the Facebook OAuth URL to use `2.12` with the upcoming deprecation of `2.5`.

**Comment by berkayk** [comment]
@kieraneglin where do you set app_id? I am getting the following error.

`The parameter app_id is required`

**Comment by harishankards** [comment]
@berkayk have you found anything? Even I'm getting that error

**Comment by cjchamado** [comment]
The "app_id" refers to the clientId of the facebook application.

```
Vue.use(VueAuthenticate, {
	providers: {
		facebook: {
			clientId: 'FB_APP_ID',
			url: 'http://your-callback-address-after-login-facebook'
		}
	}
})
```
