### ISSUE TITLE
linkedin authenticate redirect within popup?

### ISSUE THREAD

**Issue by mythicalprogrammer** [dgrubelic/vue-authenticate#131]
Hi, thank you for creating this.

Is this the default behavior where when a user login in the popup redirect the url of the popup in the popup? I was hoping 1. The popup closes and 2. the redirect uri will happen in the parent window original spa app.

If I set the `popupOptions: false` in the provider it open a new tab. Once authenticate it redirect in the new tab but not the parent spa.

Thank you.

**Comment by mythicalprogrammer** [comment]
This is a duplicate of issue #77.

**Comment by anterodev** [comment]
Some fix?

**Comment by anterodev** [comment]
Error happens here only with linkedin.
