### ISSUE TITLE
Ability to load OAuth 2 endpoint in same tab

### ISSUE THREAD

**Issue by kundanramisetti** [dgrubelic/vue-authenticate#142]
Is it currently possible to load the OAuth 2 endpoint/url in the same tab rather than opening in a new tab or a popup? I have checked the code below and it looks like it always opens the url in a new tab. 

https://github.com/dgrubelic/vue-authenticate/blob/master/src/oauth/oauth2.js#L52

@dgrubelic is this something in your roadmap?

May be it already exists and I am too blind to see it :)

**Comment by dgrubelic** [comment]
No, it does not exist because this will be impossible to implement since you would be reseting authentication state as soon as you would redirect user to provider authentication page.

This will not be supported in this library.

**Comment by Evertt** [comment]
@dgrubelic I don't understand why that's the case? Since you can save the token in local storage, you could save any state in local storage, couldn't you?
