### ISSUE TITLE
Possible Unhandled Promise Rejection: Error: Request failed with status code 404

### ISSUE THREAD

**Issue by ahmetegesel** [dgrubelic/vue-authenticate#148]
I've been trying to use this lib for authenticating to Azure AD via oauth2. It opens the popup, then I login, then it creates the authentication_code and such, but it turns out to break it when resolving the response I guess.

Here are some screenshots:

![image](https://user-images.githubusercontent.com/7090179/49480933-a29fb500-f839-11e8-92ee-b11f952324c5.png)

![image](https://user-images.githubusercontent.com/7090179/49480936-aa5f5980-f839-11e8-84e5-46de0fdd8df2.png)

and my configs are as follow:

![image](https://user-images.githubusercontent.com/7090179/49481357-9583c580-f83b-11e8-918f-c9d4e1de7ecc.png)

When I investiage the whole process from the beginning, it breaks the process when it tries to resolve the response through pooling. 

![image](https://user-images.githubusercontent.com/7090179/49481268-36be4c00-f83b-11e8-9606-7654d4e9e70d.png)

Above, it sends the params object, which doesn't have any 'then' field, to resolve function.

![image](https://user-images.githubusercontent.com/7090179/49481277-4a69b280-f83b-11e8-8c79-3e787e7608c8.png)

And then it tries to reach then function, which never exist at all.

Then it breaks it.

Please help me.

Thansk in advance

**Comment by ivanvorona** [comment]
Hello,

@ahmetegesel  did you find solution for this? 
@dgrubelic  do you know if anyone implemented Active Directory integration using this library at all?

**Comment by ahmetegesel** [comment]
No, I couldn't. Still hope you will find a way to solve this. All I could do was implementing my own lightweight small-plugin.

**Comment by ivanvorona** [comment]
thanks @ahmetegesel  - do you have your plug-in on github?

**Comment by dgrubelic** [comment]
Hey.. from what i can see, you are setting baseUrl to be wrong url. It is supposed to be url of your API where code will be exchanged for token.

@ivanvorona I don't know anyone who implemented Active Directoy with this library, but if they support oauth2, it should work out of the box.

**Comment by ahmetegesel** [comment]
> Hey.. from what i can see, you are setting baseUrl to be wrong url. It is supposed to be url of your API where code will be exchanged for token.
> 
> @ivanvorona I don't know anyone who implemented Active Directoy with this library, but if they support oauth2, it should work out of the box.

I'm currently working on some other project but I will give it a try once I get back to this one and let you know if it solves
