### ISSUE TITLE
Uncaught TypeError: Cannot redefine property: $http [vue-resource]

### ISSUE THREAD

**Issue by alfianriv** [dgrubelic/vue-authenticate#155]
`import Vue from 'vue'
import Vuex from 'vuex'
import VueAxios from 'vue-axios'
import VueResource from 'vue-resource'
import { VueAuthenticate } from 'vue-authenticate'
import config from '../config.json'
import axios from 'axios';

Vue.use(Vuex)
Vue.use(VueAxios, axios)
Vue.use(VueResource)

const vueAuthInstance = new VueAuthenticate(Vue.http, {
  baseUrl: 'http://localhost:3000',

  providers: {
    github: {
      clientId: config.auth.github.clientId,
      redirectUri: 'http://localhost:8080/auth/callback'
    },
    facebook: {
      clientId: config.auth.facebook.clientId,
      redirectUri: 'http://localhost:8080/auth/callback'
    },
    google: {
      clientId: config.auth.google.clientId,
      redirectUri: 'http://localhost:8080/auth/callback'
    },
    twitter: {
      clientId: config.auth.twitter.clientId,
      redirectUri: 'http://localhost:8080/auth/callback'
    }
  }
})

export default vueAuthInstance
`

Help me, im stuck in here

**Comment by dgrubelic** [comment]
Well, you are using both VueResource and Axios. Why do you need two http libraries?

**Comment by alfianriv** [comment]
Thanks for response @dgrubelic, i'm use this code from npmjs 
`// ES6 example
import Vue from 'vue'
import Vuex from 'vuex'
import VueAxios from 'vue-axios'
import { VueAuthenticate } from 'vue-authenticate'
import axios from 'axios';
 
Vue.use(Vuex)
Vue.use(VueAxios, axios)
 
const vueAuth = new VueAuthenticate(Vue.prototype.$http, {
  baseUrl: 'http://localhost:4000'
})`

if i'm not using VueResource i got a different error like this
Uncaught TypeError: Cannot read property 'interceptors' of undefined

so do you have a solution ?

**Comment by alfianriv** [comment]
in the first post im using Vue.http and i change to Vue.prototype.$http. Voila !!!

Thanks
