### ISSUE TITLE
Twitter Auth not Working 

### ISSUE THREAD

**Issue by anon314271** [dgrubelic/vue-authenticate#158]
I'm unable to get the twitter provider working
I've seen this issue has been open since October: https://github.com/dgrubelic/vue-authenticate/issues/143

Has anyone come up with a solution / fix / example of auth working using twitter?

Below is my code incase I've made an error

```javascript
import VueAxios from 'vue-axios'
import VueAuthenticate from 'vue-authenticate'
import axios from 'axios';


export default ({ Vue }) => {
  Vue.use(VueAxios, axios)
  Vue.use(VueAuthenticate, {
    baseUrl: 'http://localhost:8000', // Your API domain

    providers: {
      twitter: {
        clientId: 'xxxxxxxxx',
        redirectUri: 'http://localhost:8080/',
      }
    }
  })
}
```

**Comment by kkost9** [comment]
@anon314271 
hello, i have same problem
Could you figure it out?

**Comment by anon314271** [comment]
Hey there, no I didn't manage to get it working. I used [hellojs](https://github.com/MrSwitch/hello.js) instead as I found that worked, however ensure vue-router is in history mode otherwise you may run into some problems with the callback url.

Eventually I stopped using hellojs and went for a more RESTful approach. Basically I implemented the steps in the following diagram:

![Twitter Auth Flow](https://user-images.githubusercontent.com/40699523/54532427-9de1b580-497f-11e9-938a-f94e65aaeb98.png)

I'm not sure if this is still being maintained but there are some decent JS libs for oAuth out there. 

In any case, here is a helpful resource I found for vue-authenticate:
 - [ vue-authenticate-example](https://github.com/sqreen/vue-authentication-example)

**Comment by kiddick** [comment]
@mkomod could you share example app based on your diagram??

**Comment by mkomod** [comment]
I'm not sure how useful it would be given that most of the processing is done on your back-end.

On the front-end, you'd start the process off by making a ajax request:

``` axios.post("auth/twitter") ```

Then process the reponse which would be a url to twitter that lets the user sign in
You can handle this by making a pop up with the url, once the user logs in you make another request with the tokens from twitter. 

If your writing the back end implementation yourself it worth looking into some oauth libraries.

Best of luck
