### ISSUE TITLE
Can we use with JWT provider ?

### ISSUE THREAD

**Issue by nssflaos** [dgrubelic/vue-authenticate#16]
Hello,

Can we use vue-authenticate with JWT provider? or does it adhere to JWT protocol?

Thanks
Brice

**Comment by dgrubelic** [comment]
This library is built to support JWT. After successful authentication, token is stored in storage container and, if it's JWT, you can get parsed JWT payload with `this.$auth.getPayload()` or `authInstance.getPayload()` (depending on weather you are using standalone service instance or global Vue instance) method.

**Comment by nssflaos** [comment]
Hi, this is great to hear about that. Thank you for your great work.

Brice

**Comment by dgrubelic** [comment]
Thanks for your support. Closing... :)
