### ISSUE TITLE
Authentication fails on Safari, Chrome incognito mode & Mobile

### ISSUE THREAD

**Issue by YehonatanY** [dgrubelic/vue-authenticate#162]
Hi, 
I use vue-authenticate version 1.4.1.
I followed your instructions about how setting the vue-authenticate in my website. 
The flow works well on chrome in public mode
but when I try using it on chrome incognito mode / safafi / mobile (chrome & safari), I get the authentication popup (I use facebook and google providers), I enter my credentials, and when finished login, the vue-authenticate not set to be authenticated. Your code doesn't succeed to get the access token.

When inspecting your code, I see that pooling method in "OauthPopup" file succeeds to get the "this.popup.location" property, but the "hash" & "search" are empty (this.popup.location.search || this.popup.location.hash).

And since that, I get the log:
OAuth redirect has occurred but no query or hash parameters were found.

I use chrome version:
Version 73.0.3683.86 (Official Build) (64-bit)
And safari version:
Version 12.0 (14606.1.36.1.9)

**Comment by dgrubelic** [comment]
Hi, `vue-authenticate` is tested in all browsers in both public and private mode. Can you please provide code that can verify that bug is in fact due to `vue-authenticate` and not your code.

**Comment by YehonatanY** [comment]
You are right, I reviewed my code and found a problem on my side. 
Thanks!
