### ISSUE TITLE
How to center the popup auth window like the google default button ?

### ISSUE THREAD

**Issue by GreatFireWall** [dgrubelic/vue-authenticate#167]
![image](https://user-images.githubusercontent.com/4510984/58775969-d39b4f80-85fa-11e9-9d52-c45e02bfd4c0.png)

**Comment by yabuking84** [comment]
hope someone answers this soon. Dont know how to change the position of the opened window.

**Comment by draigar** [comment]
I did some research and got this. It actually places the window at the center. Hope it helps.

var top = window.screen.height - 300;
    // top = top > 0 ? top/2 : 0;
            
var left = window.screen.width - 400;
    left = left > 0 ? left/2 : 0;

Vue.use(VueAuthenticate, {
  baseUrl: store.state.rawURI, // Your API domain
  
  providers: {
    google: {
      redirectUri: store.state.callbackUrl, // Your client app URL
      popupOptions: { width: 452, height: 633, top: top, left: left }
    }
  }
});

**Comment by draigar** [comment]
I did some research and got this. It actually places the window at the center. Hope it helps.

`var top = window.screen.height - 300;
// top = top > 0 ? top/2 : 0;

var left = window.screen.width - 400;
left = left > 0 ? left/2 : 0;

Vue.use(VueAuthenticate, {
baseUrl: store.state.rawURI, // Your API domain

providers: {
google: {
redirectUri: store.state.callbackUrl, // Your client app URL
popupOptions: { width: 452, height: 633, top: top, left: left }
}
}
});`

**Comment by draigar** [comment]
var top = window.screen.height - 300;
// top = top > 0 ? top/2 : 0;

var left = window.screen.width - 400;
left = left > 0 ? left/2 : 0;

Vue.use(VueAuthenticate, {
baseUrl: store.state.rawURI, // Your API domain

providers: {
google: {
redirectUri: store.state.callbackUrl, // Your client app URL
popupOptions: { width: 452, height: 633, top: top, left: left }
}
}
});
`
i hope this helps someone.

**Comment by draigar** [comment]
To bring the window down, we could have something like this.

`var top = window.screen.height - 300;
    top = top > 0 ? top/5 : 0;`
