### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Jack85** [dgrubelic/vue-authenticate#17]
Add more providers like 
linkedin, instagram,live.. and generic oauth1 and oauth2.

**Comment by nssflaos** [comment]
+1 for OAUTH2.0

Thanks

**Comment by dgrubelic** [comment]
FYI, Instagram is already supported. I'm working on adding new providers to the library.

**Comment by dgrubelic** [comment]
Closing this issue since i'l be opening new issue for each new feature request.
