### ISSUE TITLE
Example doesn't work for me.

### ISSUE THREAD

**Issue by ivanvorona** [dgrubelic/vue-authenticate#172]
Hello, 
i am trying to use example from the repo  but authentication to fb/google doesn't work for me. it doesn't recognize providers info i added to config.json. i keep getting following error. Could you please advice?
![image](https://user-images.githubusercontent.com/18105506/59560435-a0a18480-901a-11e9-9401-dd045db6a19e.png)

**Comment by ivanvorona** [comment]
Hi @dgrubelic  When i've added clientId/clientSecrete directly into vue-authenticate.js > providers section - i was able to get through authentication. what is the purpose of config.json in the example folder then?

**Comment by kosimas** [comment]
I'm having the same issue

**Comment by dgrubelic** [comment]
`config.json` is for server example only.
