### ISSUE TITLE
Send access_token to backend?

### ISSUE THREAD

**Issue by DooMxDD** [dgrubelic/vue-authenticate#201]
Hello, I need to send access_token to backend for user login, but only code, clientId and redirectUri are sent. I'm using Laravel Passport with Socialite and it requires the access_token. Currently the request sends the code parameter. I have no idea what it's even for. Maybe I could obtain the token somehow with those "interceptors", but I couldn't make them work at all.

Many thanks for every help.

**Comment by paulocastellano** [comment]
+1
