### ISSUE TITLE
Can I auth with Github without a Popup or Tab?

### ISSUE THREAD

**Issue by AllanOricil** [dgrubelic/vue-authenticate#210]
I was looking for a way to stay in the same window while authenticating to git. I saw I can auth using a popup and also disabling it, thus using a tab. But I wanted something that would stay in the same window. Is it possible?

**Comment by EmanuelDellsen** [comment]
I have the same question but can't find the correct answer.. Keep me up to date if you end up solving it? 
Thank you in advance!

**Comment by izi-SL** [comment]
@EmanuelDellsen  @AllanOricil  pull request had been added,  https://github.com/dgrubelic/vue-authenticate/pull/219

**Comment by AllanOricil** [comment]
At the end I created my own integration flow using a server-2-server approach. You guys can check this [github auth serverless service](https://github.com/AllanOricil/github-auth-serverless) I created on AWS. Basically I use a server-2-server auth flow to retrieve an access_token whcih I later expose for an application.  In this example I'm responding the user credentials as a query parameter, but you can use cookies too.

**Comment by Piotrek98** [comment]
Try to use: `popupOptions: null` in provider options
