### ISSUE TITLE
No body in POST

### ISSUE THREAD

**Issue by philippeluickx** [dgrubelic/vue-authenticate#27]
I'm trying to get this to run. I used sattelizer before and loved it and the integration with vuex seems nice.

I got to the point where I can submit a POST request to the backend, but there's not body. Nothing is being sent.
Similar with the https://github.com/dgrubelic/vue-authenticate-site demo.

I am literally following the example codes.

**Comment by dgrubelic** [comment]
Hi @philippeluickx, can you post code gist or CodePen with issue?

**Comment by philippeluickx** [comment]
Sure!
https://gist.github.com/philippeluickx/2f6cbdb6b79ca1aab4cf2f99fb0ea37f

Also just running the vue-authenticate-site gives the same result. When inspecting the payload, there is no data being POSTed.

I am using latest vue libs (2.x)

Probably I am doing something wrong here.

Also kudos for both the fast reply and lib!

**Comment by philippeluickx** [comment]
Just a quick update.
Been messing more with the code and it seems to work now. Not sure but might be that the store is related?

Sorry for the trouble...
