### ISSUE TITLE
Unable to get it working with axios

### ISSUE THREAD

**Issue by philippeluickx** [dgrubelic/vue-authenticate#28]
I followed the instructions for adding axios, but can not get it to work.
The problem is that this.$http is undefined. Vue is pretty new to me, but it might be that "this" is the problem?
When I replace the example interceptor code this.$http to Vue.axios, the interceptor does not throw errors anymore, but the lib does (again with this.$http being undefined).

My layout is just like with vue-authenticate-site. Any help is appreciated.

https://gist.github.com/philippeluickx/1632139a90294aced85830dec3e915b3

Looking at https://github.com/imcvampire/vue-axios#usage

> This wrapper bind axios to Vue or this if you're using **single file component**.

Is there any way to hook this.$http globally?

**Comment by philippeluickx** [comment]
Found this: https://vuejs.org/v2/cookbook/adding-instance-properties.html#Real-World-Example-Replacing-Vue-Resource-with-Axios

It also seems that you don't really need the vue-axios wrapper if you do:
`Vue.prototype.$http = axios;`

But still fails on my end...

**Comment by dgrubelic** [comment]
That is basically what vue-axios wrapper does - binds Axois instance to Vue global instance.

Can you try setting up this: 

```javascript
const vueAuthInstance = new VueAuthenticate(Vue.prototype.$http, {...});
```

instead of this:

```javascript
const vueAuthInstance = new VueAuthenticate(Vue.http, {...});
```

**Comment by philippeluickx** [comment]
I tried both
`const vueAuthInstance = new VueAuthenticate(Vue.prototype.$http, {...});
`
and
`const vueAuthInstance = new VueAuthenticate(axios, {...});
`
Still the same error

**Comment by dgrubelic** [comment]
What error do you get?

**Comment by philippeluickx** [comment]
this.$http is undefined.

I get it when using it in the interceptors. When I replace them with axios, the issue is resolved. But then it fails somewhere in the vue-authenticate library where this.$http is used.

**Comment by philippeluickx** [comment]
Where exactly should the
`Vue.prototype.$http = axios;`
be defined? I added it to main.js (also tried any other possible file already).

**Comment by dgrubelic** [comment]
You have to call it **before** you initialize `VueAuthenticate` instance.

Anyway, thanks for reporting this issue, i'll take a look.

**Comment by dgrubelic** [comment]
While you wait for me to take a closer look, you can see example of how i did it with `axios` in `vue-authenticate-site`repo: https://github.com/dgrubelic/vue-authenticate-site/tree/axios-example

**Comment by philippeluickx** [comment]
I have the almost exact same setup as you have. No errors indeed on your example. Still the same issue on my setup.
Some things to note:

- I tried to replace in vue-authenticate-site the prototype manually, so by removing vue-axios and adding
`Vue.prototype.$http = axios;`
to main.js. Then there is the same issue.
Adding it to auth.js works. I'm not really understanding how prototyping works and even where "Vue" is used. I was assuming it would be globally available, but that does not seem to be the case?
- One difference is that I am using the airbnb linting rules. There we have the arrow functions required. So in the interceptor definition, you use both function and =>, while I replace everything with =>
However, this has impact on scope, no? That might be what is causing the problem?

**Comment by philippeluickx** [comment]
Confirmed, it's the arrow function that is messing up everything. Not sure what to do with that though, scoping in JS is something that makes my head spin.

2 questions:
1. Is it possible to make it work with => ?
2. Is it possible to declare the Vue.prototype.$http globally (once) so it can be used everywhere?

**Comment by dgrubelic** [comment]
Yes, arrow functions are the problem. I can provide `VueAuthenticate` class instance as a parameter as well.

Fix will be deployed soon.

**Comment by dgrubelic** [comment]
There, try to update to version 1.2.6 https://github.com/dgrubelic/vue-authenticate/releases/tag/1.2.6

**Comment by philippeluickx** [comment]
You sir, are the most quickly responding package owner I have encountered so far. Thanks a lot for the fix (it works now!) and the awesome support.

**Comment by philippeluickx** [comment]
Just a quick update on the arrow function. Learned that the shorthand for not writing e.g.
`bindRequestInterceptor: function () {`
is actually
`bindRequestInterceptor() {`
in the ES6 Airbnb linting styleguide.
This way, you keep scope the same.
