### ISSUE TITLE
Replace vue-resource with axios as default request library

### ISSUE THREAD

**Issue by dgrubelic** [dgrubelic/vue-authenticate#29]

**Comment by jkirkby91-2** [comment]
Is this enhancement going to completely drop support for vue-resource? im all in favour of that, but I am testing the latest release doing this

```
import Vue from 'vue'
import axios from 'axios'
import VueAxios from 'vue-axios'

Vue.use(VueAxios, axios)

const vueAuth = new VueAuthenticate(Vue.axios, {
  baseUrl: 'http://localhost:4000'
}) 

```
And get thrown an error 

> cannot read property 'interceptors' of undefined

**Comment by dgrubelic** [comment]
It is because you need to setup request/response interceptors (this enhancement is not implemented yet) through interceptor binding methods. This is just a task/info that i plan to do it. Currently, default interceptors bindings are for `vue-resource`. Once i implement this task, default interceptors will be for `axios`.

And no, this will not drop support for `vue-resource`, since this library allows you to have any request handling library you want (using these interceptor bindings - if library supports it).

**Comment by jkirkby91-2** [comment]
Why do interceptors have to be set when using axios? The docs suggest using them to add auth headers but, im just pushing them into axios headers on my auth success call back function like so

axios.defaults.headers.common.Authorization = 'Bearer ' + localStorage.getItem('vue-authenticate.vueauth_token')

i've consoled logged the authenticate.js constructor and above the line
    this.$http.interceptors.push(function (request, next) {

and $http is undefined hence it cant read the property of 'interceptors'

**Comment by latovicalmin** [comment]
@dgrubelic when we can expect this update for axios?

**Comment by dgrubelic** [comment]
It shouldn't be too much work, but i'm a bit booked these days su i probably won't be able to do it this week, so Maybe next week...

**Comment by dimalusa** [comment]
@dgrubelic, I'm waiting for this improvement too. 
I've tried serval configurations but without success.. 
Do you think it will be possible to work on that ?
Thanks !

**Comment by philippeluickx** [comment]
@dimalusa what problem are you having? I managed to implement this with axios. Make sure you define your interceptors (as explained in the README) and you have the correct requestDataKey configured https://github.com/dgrubelic/vue-authenticate/issues/31

You might find some inspiration in https://github.com/dgrubelic/vue-authenticate/issues/28 as well.

**Comment by edimoldovan** [comment]
Looking forward to the default axios functionality. Any progress on it?

**Comment by tdewolff** [comment]
This works for me:

`Vue.use(VueAxios, axios)
Vue.use(VueAuthenticate, {
  baseUrl: 'http://localhost:3000', // Your API domain

  providers: {
    // ...
  },

  bindRequestInterceptor: function () {
    this.$http.interceptors.request.use((config) => {
      if (this.isAuthenticated()) {
        config.headers['Authorization'] = [
          this.options.tokenType, this.getToken()
        ].join(' ')
      } else {
        delete config.headers['Authorization']
      }
      return config
    })
  },

  bindResponseInterceptor: function () {
    this.$http.interceptors.response.use((response) => {
      this.setToken(response)
      return response
    })
  }
})`

**Comment by dgrubelic** [comment]
As you may already know, from version 1.3.1 axios is default request library. Closing this issue...
