### ISSUE TITLE
Some calrifications

### ISSUE THREAD

**Issue by boustanihani** [dgrubelic/vue-authenticate#30]
Could you please clarify how this library works, a small introduction in the docs would be great.

Some thoughts & questions a developer could have:
- Where will user data be saved?
- What about routing?
- Possibility for listening to events when user is logged/unlogged?
- Could this be combined with https://auth0.com/ ?

**Comment by dgrubelic** [comment]
Hey @boustanihani,

is there something unclear about the way how to setup this library and implement it in your app?

1. What user data? You mean user profile or auth token?
2. For routing example, you can go to this example app: https://github.com/dgrubelic/vue-authenticate-site/blob/master/src/router/index.js#L49
3. I'll see if it is necessary to add support for internal events. Pretty much you can keep track of login state and trigger some actions by using Vue.js implemented reactivity (example also in the same app as above)
4. I already successfully tried to implement auth0 here (https://github.com/dgrubelic/vue-authenticate/tree/feature/auth0), but i'll have to do some more testing and review before i include it in production version of the library.

**Comment by boustanihani** [comment]
1. I mean both user profile & auth token, where are they stored?

Thanks for the clarifications

**Comment by dgrubelic** [comment]
For this library, only relevant information is auth token, and it is stored in memory/session storage/local storage (see: https://github.com/dgrubelic/vue-authenticate/tree/master/src/storage and https://github.com/dgrubelic/vue-authenticate/blob/master/src/authenticate.js#L12)

For user profile, you can store it anywhere you want. One approach is to store it in Vuex state:
https://github.com/dgrubelic/vue-authenticate-site/blob/master/src/store/auth.js#L5

Also, you can encode it directly in JWT token, and then you can fetch it using VueAuthenticate method `getPayload()` (see: https://github.com/dgrubelic/vue-authenticate/blob/master/src/authenticate.js#L138)

**Comment by boustanihani** [comment]
Thanks great work
