### ISSUE TITLE
Axios POST key is "data", not "body"

### ISSUE THREAD

**Issue by philippeluickx** [dgrubelic/vue-authenticate#31]
I noticed that my POSTs were empty (no payload) with Axios. Seems like this.options.requestDataKey is "body" by default. Just a pointer if you want to make Axios the default, you will have to change that to "data".
Source: https://github.com/mzabriskie/axios#axiosconfig

**Comment by dgrubelic** [comment]
Thanks for reminding me of that. `requestDataKey` and `responseDataKey` were added specifically for that reason.
