### ISSUE TITLE
Save profile data on login

### ISSUE THREAD

**Issue by philippeluickx** [dgrubelic/vue-authenticate#35]
Lots of backends give the profile data back with the login response (token). I'm not sure how this would be the best to implement and even if it would be appropriate within vue-authenticate. Maybe with a hook?

This is more of an approach and opinion question.
I can always do a new call to fetch the profile, but that'd be a bit of a waste.

**Comment by dgrubelic** [comment]
Hi, you can take a look at this issue for some ideas: https://github.com/dgrubelic/vue-authenticate/issues/30when you do auth

Also, you get entire response in `this.$auth.login({ email, password }).then((response) => {})` so you can do with it whatever you want. You can save it wherever you want. Same goes for `register` and `authenticate` methods. :)

**Comment by philippeluickx** [comment]
Works like a charm, thanks for the pointer!
