### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by MicroDroid** [dgrubelic/vue-authenticate#39]
They documentation needs definitely to be more clear and have much better structure how to use this library. For example, I struggle to find how and where would I receive my authorization code. Also what does `authenticate` exactly do? open up a popup? what?

**Comment by philippeluickx** [comment]
This repo helped me a lot:
https://github.com/dgrubelic/vue-authenticate-site

**Comment by designbyadrian** [comment]
I can't even get past this:

```javascript
import Vue from 'vue'
import { VueAuthenticate } from 'vue-authenticate'

console.log("VueAuthenticate",VueAuthenticate); // undefined

const vueAuthInstance = new VueAuthenticate(Vue.http, {
// ...
```

Without getting this error:

`Uncaught TypeError: _vueAuthenticate.VueAuthenticate is not a constructor`
