### ISSUE TITLE
How to test

### ISSUE THREAD

**Issue by chunge0328** [dgrubelic/vue-authenticate#4]
example to run an error?? demo?thanks

**Comment by dgrubelic** [comment]
> example to run an error??

I'm not following this first part. Can you please be more specific?

Also, demo app is in currently development and you'll find simple example app provided in this package. Just provide valid `clientId` and `clientSecret` values in `config.json` and `index.js` and you'll be able to test it.

https://github.com/dgrubelic/vue-authenticate/tree/master/example
