### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by EdozdeDandez** [dgrubelic/vue-authenticate#40]
I am trying to work with the library but I keep getting the error POST http://localhost:3000/auth/register 404 (Not Found). I even tried cloning the original repository but it is the same I can't register or login

**Comment by dgrubelic** [comment]
What is the URL of your API you are using for your app?

**Comment by EdozdeDandez** [comment]
http://localhost:3000

**Comment by dgrubelic** [comment]
Well, have you implemented that route on your API to make an code exchange for access token? This library does not provide any API functionality.

**Comment by EdozdeDandez** [comment]
Yes I did I think I have figured out the problem let me try it out then I will let you know.

**Comment by EdozdeDandez** [comment]
It worked. Thanks a lot
