### ISSUE TITLE
[documentation] for email & password login, please list sample failed and success server messages

### ISSUE THREAD

**Issue by mariusa** [dgrubelic/vue-authenticate#41]
For email & password login, please list sample failed and success server messages
so that we know in what format server should send data to work with vue-authenticate on client

Thanks!

**Comment by dgrubelic** [comment]
Hey @mariusa , thanks for this issue. 

Honestly, i don't think that this library should be involved in any error handling. Instead, on every action (login, register, authenticate) you get entire response object in `.then()` or `.catch()` handlers so you can apply any error structure you want in your application.

For that matter, i can help you to think about possible ideas on how to structure it if you are interested in that kind of help?

**Comment by mariusa** [comment]
That would be great, @dgrubelic ! Thank you!

Can't tell what to do on then()  

```
methods: {
    login() {
      this.$store.dispatch('login', {
        user: {
          email: this.email,
          password: this.password
        }
      }).then(() => {
        console.log('after login')
        // what how to access server response, how to save it to be used by the app, how to set that user is authenticated ?
        this.$router.push('')
      }).catch(() => {
        console.log('catch non-200 status, invalid login')

      })
    }
```

**Comment by dgrubelic** [comment]
First of all, you have to return login promise from your dispatched action (like this: https://github.com/dgrubelic/vue-authenticate-site/blob/master/src/store/auth.js#L22). After that, you'll be able to get response object in:

```javascript
this.$store.dispatch('login', { ...user }).then(response => {
  console.log(response);
}).catch(err => {
  console.log(err);
})
```

Have in mind that your authentication token is stored in `VueAuthenticate` service instance and is automatically appended to request headers when you do them using `vue-resource` or `axios` library (depending on your setup).

**Comment by mariusa** [comment]
Thanks Davor,

_First of all, you have to return login promise from your dispatched action_
Done. console.log shows payload.user.email and payload.user.password are set to input values (not server response)

in dispatch(), response is undefined though:
```
      }).then((response) => {
        console.log('after login')
        console.log(response)
```

Server responds:
```
{
id: 123,
role: 'admin'
}
```
We don't use JWT. Do we have to?

I was expecting to have the server response, so we that we could set isAuthenticated and $store.auth.user to that object.

Appreciate your help.

**Comment by mariusa** [comment]
We implemented JWT, but this is still undefined
```
     }).then(response => {
        console.log('after login')
        console.log(response)
```
We need to set the data sent by server in JWT in store, and access it, eg. $store.auth.user.role
isAuthenticated works properly, but not user data ("profile" in your site example)
