### ISSUE TITLE
Electron support / server removal

### ISSUE THREAD

**Issue by ludoo0d0a** [dgrubelic/vue-authenticate#42]
Do you think that wrapping your project in Electron could remove server's part.
If I understand, server.js acts as a proxy to relay post messages to providers, because CORS are not allowed from client to provider's domain.
Right ?

If so, electron support could be a great feature.
The [electron-oauth-github-vue project](https://github.com/chamerling/electron-oauth-github-vue) could be a source of inspiration.

**Comment by dgrubelic** [comment]
Hi @ludoo0d0a,

`server.js` is just part of example code to show you how to implement it on your own and it is not really included in production code.

**Comment by designbyadrian** [comment]
So how would this work without baseUrl, that is, a parallel Node.js server?

**Comment by dgrubelic** [comment]
OAuth provider must support implicit authentication flow. If that requirement is ok, you can configure your provider like this:

```javascript
new VueAuthenticate(Vue.prototype.$http, {
  providers: {
    google: {
      clientId: 'your-google-app-client-id',
      redirectUri: 'http://localhost:8080/auth/callback', // This is your client application callback url
      responseType: 'token' // This is indicator that implicit OAuth process is used
    },
  }
})
```
