### ISSUE TITLE
Facebook login error

### ISSUE THREAD

**Issue by edimoldovan** [dgrubelic/vue-authenticate#48]
Hi,

First of all, great solution. It's just what I was looking for. 
I have a question regarding integration. I ran it and I get a error saying this:
```
Possible Unhandled Promise Rejection: Error: Authentication error occurred
Stack trace:
authenticate/</<@webpack-internal:///45:1285:14
```
I go the same when I did the integration based on the readme of `vue-authenticate`. My assumption is that I am not responding as expected on the callback url. 

On the server side call Facebook does reply with all good, no issue, http 200.

What is the expected response there? Or, even better, have you seen the error before?

I am currently checking the code of `vue-authenticate` and do a step by step debug to try to figure it out, just  wanted to start a thread here while I do that.

**Comment by edimoldovan** [comment]
Since for me the issue was that the token was't where expected to be in the `response` I fixed it like this
```
bindResponseInterceptor() {
    this.$http.interceptors.response.use((response) => {
      response.access_token = response.data.access_token;
      this.setToken(response);
      return response;
    });
  },
```

I am using `axios` and `vue-axios`, so maybe that caused it. 

Any recommendation for a better fix?

**Comment by dgrubelic** [comment]
Hi @edimoldovan, thanks for your support. I have been on vacation for past few weeks so that is why there's delayed response.

This error basically means that authentication process didn't go well in Vue Authenticate library itself. Even though FB login went ok, lib couldn't find JWT token in response.

To fix this problem, you can use `requestDataKey` and `responseDataKey` options in global configuration object  (https://github.com/dgrubelic/vue-authenticate/blob/master/src/options.js#L15)

Let me know if it works. :)

**Comment by mbj36** [comment]
I followed the readme and got this error. Any help please ?

```javascript
Failed to load resource: the server responded with a status of 404 (Not Found)
vue-authenticate.es2015.js?26cf:416 Possible Unhandled Promise Rejection: Error: Authentication error occurred
    at eval (vue-authenticate.es2015.js?26cf:1284)
    at <anonymous>
```

**Comment by koddr** [comment]
@mbj36 I get that error too.

On Safari console:
```
[Error] TypeError: undefined is not a function (near '...this.$http.interceptors.push...')
	VueAuthenticate (43:1078)
	get (43:1311)
	authenticate (137:12)
	click (138:11)
```
How to fix it?

**Comment by dgrubelic** [comment]
@mbj36 Currently, library only supports explicit OAuth flow, meaning that you need to implement server-side component to exchange code for access token. You can find some examples here: https://github.com/dgrubelic/vue-authenticate/blob/master/example/server.js

I believe this is your issue.

**Comment by dgrubelic** [comment]
@edimoldovan From version 1.3.0, axios is default library for handling requests in vue-authenticate library. Can you please update and see if your problem is gone?

**Comment by edimoldovan** [comment]
@dgrubelic Sorry for the late reply. Issue solved indeed.

**Comment by Ethan0007** [comment]
@dgrubelic 

Hi i just want to ask if how can i implement it using .net core 2.1?

**Comment by Ethan0007** [comment]
Hi,

This is my authentication code for the callback.

![image](https://user-images.githubusercontent.com/12542052/50429815-ffe7cd00-08f2-11e9-9551-604d8315e4a7.png)

But I'm still getting some issue in authentcation.

![image](https://user-images.githubusercontent.com/12542052/50429828-1aba4180-08f3-11e9-954c-88bc5aac320b.png)

also i already added in Valid OAuth Redirect URIs
![image](https://user-images.githubusercontent.com/12542052/50429833-2ad22100-08f3-11e9-8b41-e30c142add99.png).

Im using 
   "vue-axios": "^2.1.4",
   "axios": "^0.18.0",

Thanks

**Comment by Ethan0007** [comment]
Hi,

When i try to open the callback url in other tab and copy the token, it will response me a token.

![image](https://user-images.githubusercontent.com/12542052/50430629-9ddd9680-08f7-11e9-84bc-6e2e7d500ea9.png)

But when in popup dialog it will give me Authenticated failed.

![image](https://user-images.githubusercontent.com/12542052/50430647-bc439200-08f7-11e9-9e67-9ce1b5931d16.png)

Can i ask some solutions or workaround on this issue.

Thanks!
