### ISSUE TITLE
Uncaught Error: Request handler instance not found

### ISSUE THREAD

**Issue by chunge0328** [dgrubelic/vue-authenticate#5]
Uncaught Error: Request handler instance not found

**Comment by dgrubelic** [comment]
That error is thrown if both `vue-resource` and `vue-axios` instance haven't been found (for now only tested with those two). You have to install one of those two libraries. Or you'll have to manually bind `Vue.prototype.$http` with your own request handler library before you initialize `vue-authenticate`.

https://github.com/dgrubelic/vue-authenticate/blob/master/src/index.js#L23

**Comment by chunge0328** [comment]
thank you!
You can use Vue-Cli to do demo.

**Comment by dgrubelic** [comment]
Great! Closing issue.
