### ISSUE TITLE
axios didnt work

### ISSUE THREAD

**Issue by angelmartz** [dgrubelic/vue-authenticate#52]
I get Error

if (!this.$http) {
            throw new Error('Request handler instance not found')
          }

**Comment by dgrubelic** [comment]
Hi @angelmartz , a bit more information about your code would be great. Can you gist code you're having problems with?

**Comment by dgrubelic** [comment]
Can you try downloading a new version (v1.3.1), it has `axios` set as default request handling library.

**Comment by dgrubelic** [comment]
Closing due to lack of information and inactivity...
