### ISSUE TITLE
Can't get Google id_token

### ISSUE THREAD

**Issue by MarDexter** [dgrubelic/vue-authenticate#53]
Hi,

I'm trying to use vue-authenticate to get the id_token from google, so that i could get the user email after right after he signs through google (without querying another google API for that).

I can't get the user email (via google) from the access_token because its not a JWT token.

When i'm trying to change the responseTpe to id_token i'm getting an error.

Do you have a workaround for it?

**The exception i'm getting**:
_Possible Unhandled Promise Rejection: Error: Authentication error occurred
    at eval (vue-authenticate.es2015.js?26cf:1284)
    at <anonymous>_

Thanks.

**Comment by dgrubelic** [comment]
Implicit `token` authentication flow is currently not supported. I'll transform this into a feature request and implement that feature.

**Comment by dgrubelic** [comment]
Simple google authenticate method with config: 
```
{ clientId: '', redirecUri: ''} 
```

will return id_token by default. No need to change `responseType` to `id_token`. You can extract it from response (this response comes from your server after code/access token exchange) like this:

```
this.$auth.authenticate('google').then(response => {
  const { id_token } = response;
})
```

Of course, you'll have to implement server-side code/token exchange like it is in example `server.js` file.

**Comment by MarDexter** [comment]
Thanks,
I eventually did exactly that.

Plus for Facebook I used "signedRequest" to get the identity token.
