### ISSUE TITLE
Browserify: VueAuthenticate is not a constructor

### ISSUE THREAD

**Issue by designbyadrian** [dgrubelic/vue-authenticate#59]
This:

```javascript
import Vue from 'vue'
import { VueAuthenticate } from 'vue-authenticate'

console.log("VueAuthenticate",VueAuthenticate); // undefined

const vueAuthInstance = new VueAuthenticate(Vue.http, {
```

gives this error:

`ncaught TypeError: _vueAuthenticate.VueAuthenticate is not a constructor`

If I import the whole module `import VueAuthenticate from vue-authenticate`, I receive a Vue plugin object, which isn't a factory according to a [similar issue](https://github.com/dgrubelic/vue-authenticate/issues/10). What am I doing wrong?

**Comment by dgrubelic** [comment]
This probably means that your Browserify setup is using common.js version of dist file, instead of es6.js version. Alternatively, you can try something like this:

```
import Vue from 'vue'
import VueAuthenticate from 'vue-authenticate'

const vueAuthInstance = VueAuthenticate.factory(Vue.http, {});
```

This should create new instance of `VueAuthenticate` object for you.

https://github.com/dgrubelic/vue-authenticate/blob/master/dist/vue-authenticate.common.js#L1333

**Comment by designbyadrian** [comment]
Thank you, I tried your example, but received a new error:

```Cannot read property 'interceptors' of undefined```

Being impatient of being stuck for so long (an afternoon is too long 😄), I tried looking into why Browserify would compile using CommonJS. I'm, indeed using Babelify, which is supposed to support ES6 syntax, and importing .vue modules works fine. It's a package installed using vue-cli. Babelify is quite old, using older presets, so I tries updating the babelrc to use the latest preset-env file, with no difference 😢 

I don't really need to use Browserify, so maybe I'll just raise the white flag and use Webpack.

**Comment by designbyadrian** [comment]
I did just find something relevant in [this issue](https://github.com/dgrubelic/vue-authenticate/issues/8), mentioning that you have to pass Vue as a whole to VueAuthenticate:

```
const authInstance = VueAuthenticate(Vue, {
  baseUrl: 'http://localhost:8000',
  loginUrl: '/oauth/token'
})
```

But I'm in the process of switching to Webpack, so will tell you when I'm done. I had issues with installing other plugins as well. I'm more used to Webpack, but Browserify just looked so neat, and I thought I could use it for a smaller project.

**Comment by designbyadrian** [comment]
Right, it was easier to get vue-authenticate to work with webpack, except that I still get to the "no interceptors" error. I wish this could be more clear in the README. It says it uses axios by default, and I can see it in the dev-dependencies.

I've tried:

```javascript
import axios from 'axios';
import { VueAuthenticate } from 'vue-authenticate';

Vue.use(axios);

const vueAuthInstance = new VueAuthenticate(Vue.http, {

// and

const vueAuthInstance = new VueAuthenticate(Vue, {
```

**Comment by designbyadrian** [comment]
I've also tried installing vue-axios:

```javascript
import Vue from 'vue';
import axios from 'axios';
import VueAxios from 'vue-axios';
import { VueAuthenticate } from 'vue-authenticate';

Vue.use(VueAxios, axios);

const vueAuthInstance = new VueAuthenticate(Vue.http, {

// and

const vueAuthInstance = new VueAuthenticate(Vue, {

```

with the same error.

**Comment by designbyadrian** [comment]
Mind you, if I try sending the whole Vue object in, I get

`Cannot read property 'request' of undefined` instead.

**Comment by dgrubelic** [comment]
I totally understand your frustration. I'm sorry you had those problems with this library.
Can you please try this and see if it works:

```javascript
import Vue from 'vue';
import axios from 'axios';
import VueAxios from 'vue-axios';
import { VueAuthenticate } from 'vue-authenticate';

Vue.use(VueAxios, axios);

// The change is from Vue.http to Vue.prototype.$http
const vueAuthInstance = new VueAuthenticate(Vue.prototype.$http, {});
```

I just tried it and it should work for you, I'll update README docs accordingly.

**Comment by designbyadrian** [comment]
Thank you! That worked!

**Comment by dgrubelic** [comment]
Again, I'm sorry this took you too much of your time. Entire README is currently in process of rewrite and will have all required information for library setup.
