### ISSUE TITLE
webpack build error

### ISSUE THREAD

**Issue by chunge0328** [dgrubelic/vue-authenticate#6]
`ERROR in static/js/0.74a7ac117d3159b549af.js from UglifyJs
Unexpected token: name (joined) [./~/vue-authenticate/src/utils.js:92,0][static/js/0.74a7ac117d3159b549af.js:133,6]`

  let normalize = function (str) {
    return str
      .replace(/[\/]+/g, '/')                             
      .replace(/\/\?/g, '?')
      .replace(/\/\#/g, '#')
      .replace(/\:\//g, '://');
  };
  return normalize(joined);

-----------------------------------------------------
Thank you

**Comment by dgrubelic** [comment]
I just released refactored build process so it should be ok now. Try it and let me know if this issue is fixed.

**Comment by dgrubelic** [comment]
This is fixed now, closing...
