### ISSUE TITLE
Vuex getter returning auth.isAuthenticated() not updating?

### ISSUE THREAD

**Issue by Dylan-Chapman** [dgrubelic/vue-authenticate#62]
How do you make a getter that returns the isAuthenticated() status? I tried what was written in the docs, but the getter value isn't updated after firing login/logout (until a page refresh). I'm assuming this has to do with how Vuex is caching the result, but I also may not understand how this is working.

**Comment by Dylan-Chapman** [comment]
Will this be looked into? I may have to look for a different library if not.

**Comment by dgrubelic** [comment]
Yes, the code in example docs has an issue. It's not working when `VueAuthenticate.isAuthenticated()` is used in computed properties. You can try something like this:

```
new Vue({
  data: {
    isAuthenticated: false,
  },
  methods: {
    login() {
      this.$auth.authenticate('github').then(res => {
        this.isAuthenticate = this.$auth.isAuthenticated();
      })
    }
  }
})
```

or you can try using `this.$auth.isAuthenticated()` directly in your views.

**Comment by dgrubelic** [comment]
@Dylan-Chapman Can we consider this issue to be resolved?
