### ISSUE TITLE
How can I run example 

### ISSUE THREAD

**Issue by riaydh06** [dgrubelic/vue-authenticate#63]
I want to run your example but I can't. So I need documentation to run your example.

**Comment by egorzekov** [comment]
Hello @riaydh06,

As for me, I didn't have problems to run examples from README file - https://github.com/dgrubelic/vue-authenticate. Therefore, for me, as for an usual user, it's not clear what additional documentation you need.

Also, could you please provide more details regarding your attempts (e.g. source code or stack trace)?

**Comment by waqasafzal** [comment]
i'm trying to run example at localhost but unable to run example successfully because when i try to get auth from google, my request get "405 method not allowed".
request url : http://localhost:8080/auth/google
what i am doing wrong...

**Comment by dgrubelic** [comment]
@waqasafzal Please do not spam issues.
