### ISSUE TITLE
Does it work with vue2?

### ISSUE THREAD

**Issue by naveen84123** [dgrubelic/vue-authenticate#64]
When I am tring to use this packag in my main.js file and the calling function in another component it is giving an error.
main.js
Vue.use(VueAuthenticate, {
        baseUrl: 'http://localhost:8000', // Your API domain
        providers: {
            github: {
                clientId: '0af65d0d91717c74037e',
                redirectUri: 'http://localhost:8087/auth/callback' // Your client app URL
            }
        }
    });

Login.vue
    authenticate(provider) {
                    this.$auth.authenticate(provider).then(function () {
                        
                    });
                },

and I am getting this error.
"Exception: TypeError: Cannot read property 'use' of undefined at VueAuthenticate.bindRequestInterceptor (webpack-internal:///466:463:37) at new VueAuthenticate (webpack-internal:///466:1102:41) at VueComponent.get (webpack-internal:///466:1318:29) at VueComponent.remoteFunction (<anonymous>:2:14)"

**Comment by dgrubelic** [comment]
Can you please gist your code properly. I'd like to see full `Login.vue` and `main.js` files.

**Comment by dgrubelic** [comment]
Not enough information to resolve issue, closing...
