### ISSUE TITLE
Custom error messages needed with rejected promise.

### ISSUE THREAD

**Issue by cpxPratik** [dgrubelic/vue-authenticate#65]
On `authenticate.js`, while authenticating with banckend api it returns the generic error message "Authentication error occurred" with rejected promise whether popup closed or when cannot connect to api backend. I want to display flash notice "Cannot connect to server", when backend is not running. With same generic message, i cannot do that.
With `.catch((error) => {
        reject(error)
      })`, I get the relevant error and also can set custom error message with interceptor on response error. I hope more suitable solution is provided so that we can choose for abstract error message like now or custom error so we can know whether it is network error or closed/canceled popup.

**Comment by dgrubelic** [comment]
Hi  @cpxPratik, thanks for reporting this. I'll fix it in next version.

**Comment by cpxPratik** [comment]
Fixed with v1.3.4.
https://github.com/dgrubelic/vue-authenticate/commit/166db4046e28281d540d2ab0b3881a2e88d39930
