### ISSUE TITLE
what state.js should look like

### ISSUE THREAD

**Issue by arysom** [dgrubelic/vue-authenticate#7]
Excuse me, but do you really mean state.js or store.js ...?

https://github.com/dgrubelic/vue-authenticate/commit/36fb76fe304a70da14998b33a9bc420e563723dc#diff-04c6e90faac2675aa89e2176d2eec7d8R153

**Comment by dgrubelic** [comment]
Yes, you are right... My bad. It's fixed now. Thanks for reporting this.

**Comment by arysom** [comment]
Thank you, great work!
