### ISSUE TITLE
Uncaught TypeError: Cannot read property 'login' of undefined

### ISSUE THREAD

**Issue by pirmax** [dgrubelic/vue-authenticate#71]
**Error:**

> Uncaught TypeError: Cannot read property 'login' of undefined
>     at VueComponent.login (135:72)
>     at Proxy.boundFn (vue.esm.js?efeb:187)
>     at click (Login.vue?8b9b:195)
>     at invoker (vue.esm.js?efeb:1937)
>     at HTMLButtonElement.fn._withTask.fn._withTask (vue.esm.js?efeb:1772)

**Code:**

`<v-btn color="orange darken-1" flat @click.native="login()">Login</v-btn>`

```
methods: {
    login () {
      this.$auth.login(this.user).then(() => {
        alert('ok')
      }).catch(() => {
        alert('error')
      })
    }
  }
```

**Comment by dgrubelic** [comment]
I see you submitted your question on StackOverflow, and since this question is not really related to this library but with your code, i'm going to close this issue...
