### ISSUE TITLE
Uncaught TypeError: Cannot read property 'login' of undefined

### ISSUE THREAD

**Issue by pirmax** [dgrubelic/vue-authenticate#72]
I use always your package but I have somes problems :/

**My code:**
- https://pastebin.com/YNq21nkc
- https://pastebin.com/vyvm3MLA
- https://pastebin.com/SQtVx6Kg

**My error:**

> Uncaught TypeError: Cannot read property 'login' of undefined
    at VueComponent.login (Login.vue?7f92:84)
    at Proxy.boundFn (vue.esm.js?efeb:187)
    at click (Login.vue?2018:201)
    at invoker (vue.esm.js?efeb:1937)
    at HTMLButtonElement.fn._withTask.fn._withTask (vue.esm.js?efeb:1772)

**Comment by JamesJefferyUK** [comment]
Please don't close issues without leaving an explanation of how you resolved. It's useless to people coming from Google with the same/similar issues. It would help the open source community if you was to provide a solution to your own problem before closing.
