### ISSUE TITLE
Google Oauth question

### ISSUE THREAD

**Issue by sajax88** [dgrubelic/vue-authenticate#75]
Hi there, thanks for your magnificent lib! Need a little help with using it, though ))

I have a single-page app and a php backend. Authentication by google oauth2 goes properly - I get a popup, then I get redirected here and there, and at last I'm on my redirect page (rendered on backend, with php) and I have my google token. But after closing the popup I get "Authentication error occurred" error. I guess that somehow I should pass this acquired token back to Vue, but cannot quite understand how to do it. Maybe put it into cookie or something? A small example would be great. Thanks again!

**Comment by sajax88** [comment]
Got it! I'd set incorrect redirectUri - should have been "window.location.origin". Now works like a charm!

**Comment by dgrubelic** [comment]
If you have latest version, `redirectUri` should be set to `window.location.origin` by default. https://github.com/dgrubelic/vue-authenticate/blob/master/src/options.js#L71
