### ISSUE TITLE
[ cookieStorage: { secure: true } ] doesn't work.

### ISSUE THREAD

**Issue by ChanMinPark** [dgrubelic/vue-authenticate#80]
When I configure vue-authenticate,
If I set [ cookieStorage: { secure: true } ] , authenticate function doesn't work.

Below error is occured.
```
vue-authenticate.es2015.js:459 Possible Unhandled Promise Rejection: Error: Authentication failed
    at vue-authenticate.es2015.js:1380
    at <anonymous>
```

but, If I set 'secure' to 'true', authenticate function does work well.

How can I set 'secure' to 'true'??

**Comment by dgrubelic** [comment]
Are you running this on localhost or on production site?

> but, If I set 'secure' to 'true', authenticate function does work well.

and then...

> How can I set 'secure' to 'true'??

I'm a bit confused here? First you can set it, and then you can't?

**Comment by ChanMinPark** [comment]
Oh! I didn't know if I'm in localhost, secure cookie doesn't work.
When I am running my site in production, secure cookie does work well.
Thank you :)
