### ISSUE TITLE
Custom authenticate logic

### ISSUE THREAD

**Issue by trrete** [dgrubelic/vue-authenticate#86]
Hi,
I need a method that can use my own logic in function `authenticate`.

For example line 220 of `src/authenticate.js`

```javascript
      // You can set some like this.
      if (needToSetOwnAuthencateLogin) {
        return providerInstance.init(userData);
      }

      return providerInstance.init(userData).then((response) => {
        this.setToken(response)

        if (this.isAuthenticated()) {
          return resolve(response)
        } else {
          return reject(new Error('Authentication failed'))
        }
      }).catch(err => reject(err))
```

I need this improvements as soon as possibile.
Regards,

Trrete.

PS: Remember to expose `reject` and `resolve` methods.

**Comment by dgrubelic** [comment]
I'm not sure what you need here so maybe the best way would be to fork this repo and implement whatever custom logic you need.
