### ISSUE TITLE
Allow specifying scopes from provider config

### ISSUE THREAD

**Issue by kieraneglin** [dgrubelic/vue-authenticate#93]
Since everyone's needs are different, I don't think that hardcoding the scopes in `options.js` is the ideal solution.

Instead, I propose that the predefined scopes stay as-is, but can be overwritten by your provider config like so:

```javascript
  providers: {
    github: {
      clientId: '',
      scope: ['repo:status', 'repo_deployment'] // completely overwriting the predefined scopes
    }
  }
```
If there is interest (and I get the go-ahead from @dgrubelic), I could try to create a PR.

**Comment by dgrubelic** [comment]
As far as i know, scope parameter can be overridden just like any other config parameter. Please, try it yourself, if this doesn't work, then let me know and i'll see what's going on. (BTW, i just teste this and it works like it should)

**Comment by kieraneglin** [comment]
Hmm, very strange.  It was not working for me as you described, but I'll investigate again.  I'll close until then!
