### ISSUE TITLE
How to set tokenName to a child object of json response?

### ISSUE THREAD

**Issue by NimzyMaina** [dgrubelic/vue-authenticate#99]
Hi,
I'm facing the following problem. The response i get from the server is inside a "data" node.

```json
{
   "data":{
      "id":1,
      "first_name":"John",
      "last_name":"Doe",
      "email":"john@gmail.com",
      "phone":"0712345678",
      "profile":"http://example.com/profiles/no_image.jpg",
      "api_token":"HZv2TnCyZh6iwwCdt1jjkKccFWfs3qaveL9Bu5Z4qi2Z9c9YAfbUfKXuOTLbcishAna",
      "roles":[
         "User"
      ]
   }
}
```

In the example, this is the response given

```json
{
   "id":1,
   "name":"John Doe",
   "email":"john.doe@domain.com",
   "created_at":"2018-2-4 10:40:00",
   "access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIx..."
}
```

How do I change my tokenName or responseDataKey to suite my response?

I have tried 
```json
{
   "tokenName": "data.api_token"
}
```

Kindly assist.
Thanks in advance.

**Comment by dgrubelic** [comment]
This will actually be done automatically using `responseDataKey` in options https://github.com/dgrubelic/vue-authenticate/blob/master/src/options.js#L21

Basically, you should only have to change `tokenName` to "api_token" and it should work.

**Comment by NimzyMaina** [comment]
@dgrubelic The issue is that my token is `data.data.api_token` as opposed to what this library tries to get which is `data.api_token` so I resorted to calling the setToken method manually with the appropriate json node `this.$auth.setToken(response.data)`. 

If it would be possible to set 
```json
{
"responseDataKey": "data.data"
}
``` 
then that would be awesome.

**Comment by dgrubelic** [comment]
In my experience, when you have something like `data.data.api_token`, then it must be something wrong with the architecture of your app or response. Do you really have to send it in double `data` object?

For now, this is not possible, and since this is not really a common case to have response structured like this, I don't think I'll add it to the library anytime soon.

**Comment by NimzyMaina** [comment]
@dgrubelic It is a Fractal standard to send json responses like that. It uses two json nodes. One for data hence the "data" and another for meta data called "meta" for things like pagination etc. It's not a must to have this feature but since Vuejs and Laravel go hand in hand it wouldn't be bad to have it.
